### ISSUE TITLE
kiss user isn't in the sudoers file

### ISSUE THREAD

**Issue by eudaldgr** [abbbi/kiss-bootstrap#1]

**Comment by abbbi** [comment]
currently only the "vagrant" user gets added to the sudoers file, ..

**Comment by eudaldgr** [comment]
So, i need to login as 'vagrant' to install packages? Why is needed the 'kiss' user also?

**Comment by eudaldgr** [comment]
'vagrant' have privilege scalation and 'kiss' doesn't, issue solved.
